apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: symfony-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: symfony-replica
  minReplicas: 2
  maxReplicas: 9
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
