apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: symfony-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: symfony-replica
  minReplicas: 2
  maxReplicas: 18
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 18
    scaleUp:
      stabilizationWindowSeconds: 9
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
