apiVersion: v1
kind: Service
metadata:
  name: database-node
spec:
  selector:
    app: database-pod
  ports:
    - name: tcp-5432
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
