apiVersion: v1
kind: Service
metadata:
  name: symfony-balancer
spec:
  internalTrafficPolicy: Local
  selector:
    app: symfony-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
