apiVersion: batch/v1
kind: Job
metadata:
  name: siege-load-test
spec:
  template:
    spec:
      containers:
        - name: siege
          image: yokogawa/siege
          args:
            - "siege"
            - "-c900"
            - "-t3M"
            - "symfony-balancer/en/blog"
      restartPolicy: OnFailure
  backoffLimit: 3
  parallelism: 3
  completions: 9
