apiVersion: batch/v1
kind: Job
metadata:
  name: siege-load-test
spec:
  template:
    spec:
      containers:
        - name: siege
          image: yokogawa/siege
          args:
            - "siege"
            - "-c900"
            - "-t3M"
            - "https://symfony-node/en/blog"
      restartPolicy: Never
  backoffLimit: 3
  parallelism: 3
